name = "CanRad"
uuid = "aeb86711-de0f-4108-877d-aa9de166218e"
authors = ["Clare Webster"]
version = "0.13.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
Chain = "8be319e6-bccf-4806-a6f7-6fae938471bc"
Conda = "8f4d0f93-b110-5947-807f-2305c1781a2d"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Format = "1fa38f19-a742-5d3f-a2b9-30dd87b9d5f8"
Images = "916415d5-f1e6-5110-898d-aaa5f9f070e0"
Impute = "f7bf1975-0170-51b9-8c5f-a992d46b9575"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
LasIO = "570499db-eae3-5eb6-bdd5-a5326f375e68"
LazIO = "c3605908-9f0f-11e8-0a72-0d361c15a277"
MAT = "23992714-dd62-5051-b70f-ba57cb901cac"
MarketTechnicals = "4f8c86c6-9e40-5506-9807-98571cb48bc8"
NCDatasets = "85f8d34a-cbdd-5861-8df4-14fed0d494ab"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
PolygonOps = "647866c9-e3ac-4575-94e7-e3d426903924"
Proj = "c94c279d-25a6-4763-9509-64d165bea63e"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
SpatialFileIO = "ab380219-86f4-46ea-9ab2-f0efd05bc343"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
CSV = "0.10.15"
MAT = "0.10.7"
Proj = "1.7.2"
SpatialFileIO = "0.7.0"
julia = "1.7,1.8,1.9,1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
