name = "CanRad"
uuid = "aeb86711-de0f-4108-877d-aa9de166218e"
authors = ["Clare Webster"]
version = "0.8.0"

[deps]
Chain = "8be319e6-bccf-4806-a6f7-6fae938471bc"
Conda = "8f4d0f93-b110-5947-807f-2305c1781a2d"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Formatting = "59287772-0a20-5a39-b81b-1366585eb4c0"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
LasIO = "570499db-eae3-5eb6-bdd5-a5326f375e68"
LazIO = "c3605908-9f0f-11e8-0a72-0d361c15a277"
NCDatasets = "85f8d34a-cbdd-5861-8df4-14fed0d494ab"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
PolygonOps = "647866c9-e3ac-4575-94e7-e3d426903924"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
SpatialFileIO = "ab380219-86f4-46ea-9ab2-f0efd05bc343"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
Conda = "1.3"
DataFrames = "1.2.0"
DataStructures = "0.17"
Dates = "1.0"
DelimitedFiles = "1.0"
Distributions = "0.23.5"
Formatting = "0.4"
Interpolations = "0.12"
PyCall = "1.91"
SpatialFileIO = "0.6.0"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
